PL/Controllers/LoginAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
namespace PL.Controllers
{
    public class LoginAdminController : Controller
    {
        // GET: LoginAdmin
        public ActionResult Login()
        {
            Session["resultLogin"] = 0;
            Session["AdminLog"] = null;
            Session["PerfilAdminLog"] = null;
            Session["Permisos"] = null;
            Session["Modulos"] = null;
            Session["IdResponsable"] = null;

            return View();
        }
        public ActionResult AutenticarAdmin(ML.Administrador admin)
        {
            string HtmlCodeAlertProgress = "";
            HttpRuntime.Cache.Add("statusReporteFinal", HtmlCodeAlertProgress, null, System.Web.Caching.Cache.NoAbsoluteExpiration, TimeSpan.FromHours(8),
                System.Web.Caching.CacheItemPriority.High, null);
            Session["statusReporte"] = "";
            Session["EmailCompleted"] = 0;
            Session["EstatusEmails"] = 0;
            var result = BL.Administrador.AutenticarAdmin(admin);

            Session["CompanyDelAdminLog"] = result.CompanyDelAdmin;
            Session["IdAdministradorLogeado"] = result.CURRENTIDADMINLOG;

            Session["SuperAdmin"] = result.IsSuperAdmin;
            Session["IdResponsable"] = BL.Administrador.isResponsable(admin.UserName).NewId;
            BL.Seguridad seguridad = new BL.Seguridad();
            Session["ps"] = seguridad.EncriptarCadena(admin.Password);
            try
            {
                if (result.PerfilesList != null || result.PerfilesList.Count != 0)
                {
                    Console.WriteLine();
                }
            }
            catch (Exception ex)
            {
                return Json("error");
            }

            if (result.PerfilesList != null || result.PerfilesList.Count != 0)
            {
                foreach (string item in result.PerfilesList.ToList())
                {
                    if (item == "Administrador Master")
                    {
                        Session["Master"] = true;
                    }
                    else
                    {
                        Session["Master"] = false;
                    }
                }
                /****************GetCompaniesForPermission*****************************/
                Session["CurrentIdAdminLog"] = result.CURRENTIDADMINLOG;
                var getCompanies = BL.Administrador.GetCompaniesForPermisos(result.CURRENTIDADMINLOG);


                ViewBag.CompaniesPermisos = getCompanies.Objects;
                Session["CompaniesPermisos"] = getCompanies.Objects;
                /********************End GetCompanies***************************/


                if (result.Correct == true)
                {
                    //result contiene las acciones que se pueden realizar por el usuario
                    string Nombre = ((ML.PerfilModulo)result.Object).Administrador.Empleado.Nombre;
                    string ApellidoP = ((ML.PerfilModulo)result.Object).Administrador.Empleado.ApellidoPaterno;
                    string ApellidoM = ((ML.PerfilModulo)result.Object).Administrador.Empleado.ApellidoMaterno;

                    string color = ((ML.Administrador)result.DataColors).Company.Color;
                    string logo = ((ML.Administrador)result.DataColors).Company.LogoEmpresa;

                    Session["color"] = color;
                    Session["logo"] = logo;
                    //para obtener perfil sería iterar sobre un objects para obtener uno o los que salgan Objects.Aux
                    //string PerfilD4U = ((ML.PerfilModulo)result.Object).PerfilD4U.Descripcion;

                    Session["IdEmpleadoLog"] = result.CURRENT_IDEMPLEADOLOG;
                    Session["AdminLog"] = Nombre + " " + ApellidoP + " " + ApellidoM;
                    Session["PerfilAdminLog"] = result.PerfilesList;
                    Session["Permisos"] = result.ObjectsPermisos;
                    Session["Modulos"] = result.ObjectsAux;
                    BL.NLogGeneratorFile.logAccesCMS(admin.UserName, Nombre + " " + ApellidoP + " " + ApellidoM);
                    return Json("success");
                }
                else
                {
                    ViewBag.ErrorMessage = "Claves de acceso no válidas";
                    Session["resultLogin"] = 1;
                    return Json("error");
                }

            }
            else
            {
                return Json("error");
            }

            

            
        }

        public JsonResult AutenticarAdmin_(ML.Administrador admin, HttpSessionStateBase Session)
        {
            string HtmlCodeAlertProgress = "";
            HttpRuntime.Cache.Add("statusReporteFinal", HtmlCodeAlertProgress, null, System.Web.Caching.Cache.NoAbsoluteExpiration, TimeSpan.FromHours(8),
                System.Web.Caching.CacheItemPriority.High, null);
            Session["statusReporte"] = "";
            Session["EmailCompleted"] = 0;
            Session["EstatusEmails"] = 0;
            var result = BL.Administrador.AutenticarAdmin(admin);

            Session["CompanyDelAdminLog"] = result.CompanyDelAdmin;
            Session["IdAdministradorLogeado"] = result.CURRENTIDADMINLOG;

            Session["SuperAdmin"] = result.IsSuperAdmin;
            BL.Seguridad seguridad = new BL.Seguridad();
            Session["ps"] = seguridad.EncriptarCadena(admin.Password);

            try
            {
                if (result.PerfilesList != null || result.PerfilesList.Count != 0)
                {
                    Console.WriteLine();
                }
            }
            catch (Exception ex)
            {
                return Json("error");
            }

            if (result.PerfilesList != null || result.PerfilesList.Count != 0)
            {
                foreach (string item in result.PerfilesList.ToList())
                {
                    if (item == "Administrador Master")
                    {
                        Session["Master"] = true;
                    }
                    else
                    {
                        Session["Master"] = false;
                    }
                }
                /****************GetCompaniesForPermission*****************************/
                Session["CurrentIdAdminLog"] = result.CURRENTIDADMINLOG;
                var getCompanies = BL.Administrador.GetCompaniesForPermisos(result.CURRENTIDADMINLOG);


                ViewBag.CompaniesPermisos = getCompanies.Objects;
                Session["CompaniesPermisos"] = getCompanies.Objects;
                /********************End GetCompanies***************************/


                if (result.Correct == true)
                {
                    //result contiene las acciones que se pueden realizar por el usuario
                    string Nombre = ((ML.PerfilModulo)result.Object).Administrador.Empleado.Nombre;
                    string ApellidoP = ((ML.PerfilModulo)result.Object).Administrador.Empleado.ApellidoPaterno;
                    string ApellidoM = ((ML.PerfilModulo)result.Object).Administrador.Empleado.ApellidoMaterno;

                    string color = ((ML.Administrador)result.DataColors).Company.Color;
                    string logo = ((ML.Administrador)result.DataColors).Company.LogoEmpresa;

                    Session["color"] = color;
                    Session["logo"] = logo;
                    //para obtener perfil sería iterar sobre un objects para obtener uno o los que salgan Objects.Aux
                    //string PerfilD4U = ((ML.PerfilModulo)result.Object).PerfilD4U.Descripcion;

                    Session["IdEmpleadoLog"] = result.CURRENT_IDEMPLEADOLOG;
                    Session["AdminLog"] = Nombre + " " + ApellidoP + " " + ApellidoM;
                    Session["PerfilAdminLog"] = result.PerfilesList;
                    Session["Permisos"] = result.ObjectsPermisos;
                    Session["Modulos"] = result.ObjectsAux;
                    BL.NLogGeneratorFile.logAccesCMS(admin.UserName, Nombre + " " + ApellidoP + " " + ApellidoM);
                    return Json("success");
                }
                else
                {
                    ViewBag.ErrorMessage = "Claves de acceso no válidas";
                    Session["resultLogin"] = 1;
                    return Json("error");
                }

            }
            else
            {
                return Json("error");
            }




        }

        public ActionResult IsLogged()
        {
            //logError => ex.message
            //statusTarea => Task.status
            Session["getErrorMessage"] = Convert.ToString(HttpRuntime.Cache.Get("logError"));
            var sessionEmailStatus = Convert.ToString(Session["EstatusEmails"]);//1 success: 0 nada: 2 error
            string session = Convert.ToString(Session["AdminLog"]);
            string statusCache = Convert.ToString(HttpRuntime.Cache.Get("status"));

            //Validar quien ve la notificacion
            string UsuarioEnvíaEncuesta = Convert.ToString(Session["UsuarioEnvia"]);
            string usuarioActual = Convert.ToString(Session["AdminLog"]);

            if (UsuarioEnvíaEncuesta != "")
            {
                Console.Write("");
            }

            if (session == null)
            {
                return Json("error");//Session caducada
            }
            else if (session == "")
            {
                return Json("error");//Session caducada
            }
            if (session != null && session != "" && statusCache == "")
            {
                return Json("success");//Session activa
            }
            else if(session != null && session != "" && statusCache == "1" && UsuarioEnvíaEncuesta == usuarioActual)
            {

PL/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult GetLogin()
        {
            var res = BL.Encuesta.Demo();
            return View("Login");
        }
    }
}

PL/Views/LoginAdmin/Login.cshtml
@using Newtonsoft.Json
@model ML.Administrador
@{  
    ViewBag.Title = "Login CMS - Encuestas";
    Layout = null;
}
<!DOCTYPE html>

<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @Styles.Render("~/bundles/cssAdmin")   
    
    <!-- Title -->
    <title>Bienvenido | Diagnostic 4U</title>
</head>
<body>
    <noscript>
        <style type="text/css">
            #wrapper {
                display: none;
            }
        </style>
        <div class="noscriptmsg">
            Esta pagina funciona con librerias javascript, no se detecto ninguna libreria en tu equipo
        </div>
    </noscript>
    <main id="wrapper">
        <section id="slider">
            <!-- Swiper -->
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide" style="background-image: url('../../img/background/bg-login-1.jpg');"></div><!--.swiper-slide-->
                    <div class="swiper-slide" style="background-image: url('../../img/background/bg-login-2.jpg');"></div><!--.swiper-slide-->
                    <div class="swiper-slide" style="background-image: url('../../img/background/bg-login-1.jpg');"></div><!--.swiper-slide-->
                    <div class="swiper-slide" style="background-image: url('../../img/background/bg-login-2.jpg');"></div><!--.swiper-slide-->
                </div><!--.swiper-wrapper-->
            </div><!--.swiper-container-->
        </section>


        <div class="form-wrapper">
            <div class="form-box">
                <img src="~/img/logo.png" class="img-fluid logo-form" alt="Logo">
                <h1 class="title-form-box">Iniciar sesión</h1>
                <div class="form-group mb-4">
                    @*<input type="text" class="form-control form-control-lg UserName" id="userLogin" placeholder="Usuario:">*@
                    @Html.TextBoxFor(model => model.UserName, htmlAttributes: new { @type = "text", @class = "form-control form-control-lg UserName", @id = "userLogin", @placeholder = "Usuario:" })
                </div>
                <div class="form-group mb-4">
                    @*<input type="password" class="form-control form-control-lg Pass" id="passwordLogin" placeholder="Contraseña:">*@
                    @Html.TextBoxFor(model => model.Password, htmlAttributes: new { @type = "password", @class = "form-control form-control-lg Pass", @id = "passwordLogin", @placeholder = "Contraseña:" })
                </div>
                <a href="@Url.Action("ForgotPassword", "Account")" class="text-forgot">¿Olvidaste tu contraseña?</a>
            </div>
            @*<a href="#" class="btn btn-login btn-block" onclick="Autenticar()">Entrar</a>*@
            <input type="submit" value="Entrar" class="btn btn-login btn-block" style="min-width:100%" onclick="Autenticar()" />
        </div>

        <div class="text-slide">
            <h2 class="title-message">Mejora la interacción</h2>
            <p class="desc-message">con el cliente tomando decisiones<br>basadas en conocimientos generados</p>
        </div>
    </main>


    @Scripts.Render("~/bundles/jqueryAdmin")


    <script src="~/scripts/swiper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        var swiper = new Swiper('.swiper-container', {
            spaceBetween: 0,
            effect: 'fade',
            loop: true,
            centeredSlides: true,
            autoplay: {
                delay: 3500,
                disableOnInteraction: false,
            }
        });
    </script>
    <script>

        $(document).ready(function () {

            var resultLogin = @Session["resultLogin"];
            if (resultLogin != 0) {

                swal({
                    title: "Claves de acceso no válidas",
                    text: "",
                    type: "error",
                    icon: "error",
                });

            }


            //$("#userLogin").on('paste', function (e) {
            //    e.preventDefault();
            //    //alert('Esta acción está prohibida');
            //});

            //$("#userLogin").on('copy', function (e) {
            //    e.preventDefault();
            //    //alert('Esta acción está prohibida');
            //});

            //$("#passwordLogin").on('paste', function (e) {
            //    e.preventDefault();
            //    //alert('Esta acción está prohibida');
            //});

            //$("#passwordLogin").on('copy', function (e) {
            //    e.preventDefault();
            //    //alert('Esta acción está prohibida');
            //});
        });

        function validarClaves() {
            var userName = $('.UserName').val();
            var pass = $('.Pass').val();

            if (userName == null || pass == null || userName == "" || pass == "") {
                swal("Debe ingresar sus claves de acceso", "", "error");
                return false;
            }
            else {
                Autenticar();
            }

        }

        function Autenticar() {
            var userName = $('.UserName').val();
            var pass = $('.Pass').val();

            if (userName == "" || userName == null || pass == null || pass == "") {
                swal("Debe ingresar sus claves de acceso", "", "error");
            }
            else{

                let ModelAdministrador = {
                    username: userName,
                    password: pass
                };

                var MLAdministrador = JSON.stringify(ModelAdministrador);

                $.ajax({

                    type: 'POST',
                    data: MLAdministrador, traditional: true,
                    url: '@Url.Action("AutenticarAdmin", "LoginAdmin")',
                    contentType: 'application/json; charset=utf-8',
                    complete: function (Response) {
                        if (Response.responseText == '"error"') {
                            swal("Claves de acceso no válidas", "", "error");
                        }
                        if (Response.responseText == '"success"') {
                            //console.log('suxccess');
                            localStorage["usuario"] = userName;
                            window.location.href = "/Dashboard/Dashboard/";
                        }

                    }
                });

            }
        }
        function sendCode() {
            var code = '<h3 class="box-header-title">Encuesta corta Satisfacción al cliente</h3><p class="box-header-paragraph">Breve descripción de la encuesta, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu</p>';
            var instr = '<h3 class="box-header-title">Encuesta corta Satisfacción al cliente</h3><p class="box-header-paragraph">Breve descripción de la encuesta, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu</p>';
            let model = {
                descripcion: code,
                instruccion: instr
            }

            $.ajax({
                url: '@Url.Action("getHtml", "LoginAdmin")',
                data: model,
                success: function (Response) {
                    console.log(Response);
                }
            });

        }
    </script>


</body>
</html>