PL/Controllers/PlanesDeAccionController.cs
using Microsoft.Office.Interop.Excel;
using Spire.Xls;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Hangfire;

namespace PL.Controllers
{
    /// <summary>
    /// Controlador del Módulo de Planes de Acción
    /// </summary>
    public class PlanesDeAccionController : Controller
    {
        #region Generales Modulo
        /// <summary>
        /// Agrega los promedios de cada categoria en una encuesta, base de datos y area especifica
        /// </summary>
        /// <param name="promediosCategorias"></param>
        /// <returns></returns>
        public JsonResult GuardarPromediosPorCategoria(List<ML.PromediosCategorias> promediosCategorias)
        {
            string UsuarioActual = Session["AdminLog"] == null ? "Invitado" : Session["AdminLog"].ToString();
            var result = BL.PlanesDeAccion.GuardarPromediosPorCategoria(promediosCategorias, UsuarioActual);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Vista del listado de encuestas
        /// </summary>
        /// <returns></returns>
        public ActionResult GetEncuestas()
        {
            return View();
        }
        /// <summary>
        /// Api con el listado de encuestas de clima laboral
        /// </summary>
        /// <returns></returns>
        public JsonResult GetEncuestasClima()
        {
            var result = BL.PlanesDeAccion.GetEncuestasClima();
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Vista de configuración del machote de acciones de mejora
        /// </summary>
        /// <param name="key">UID</param>
        /// <param name="IdEncuesta"></param>
        /// <param name="IdBaseDeDatos"></param>
        /// <param name="AnioAplicacion"></param>
        /// <returns></returns>
        public ActionResult Index(string key = "0", string IdEncuesta = "0", string IdBaseDeDatos = "0", string AnioAplicacion = "0")
        {
            ML.PlanDeAccion planDeAccion = new ML.PlanDeAccion();
            planDeAccion.IdEncuesta = Convert.ToInt32(IdEncuesta);
            planDeAccion.IdBaseDeDatos = Convert.ToInt32(IdBaseDeDatos);
            planDeAccion.AnioAplicacion = Convert.ToInt32(AnioAplicacion);
            planDeAccion.key = key;
            return View(planDeAccion);
        }
        /// <summary>
        /// Muestra el configurador de notificaciones
        /// </summary>
        /// <returns></returns>
        public ActionResult Notificaciones(string IdPlanDeAccion = "0")
        {
            return View(new ML.PlanDeAccion() { IdPlanDeAccion = Convert.ToInt32(IdPlanDeAccion) });
        }
        /// <summary>
        /// Envio de email customizado por el usuario
        /// </summary>
        /// <param name="IdPlanDeAccion"></param>
        /// <param name="email"></param>
        /// <returns></returns>
        public JsonResult ConfiguraNotificacion(int IdPlanDeAccion, ML.Email email)
        {
            bool result = false;
            if (string.IsNullOrEmpty(email.Frecuencia))
            {
                // Job inicia y olvida
                BackgroundJob.Enqueue(() => BL.PlanesDeAccion.EnvioEmailCustom(IdPlanDeAccion, email.Priority, email.Subject, email.Plantilla));
                result = true;
            }
            else
            {
                // Job recurrente
                string uid = "IdPlan_" + IdPlanDeAccion + "_" + Guid.NewGuid().ToString();
                result = BL.PlanesDeAccion.AgregarJobNotificacionesPDA(IdPlanDeAccion, uid, Session["AdminLog"].ToString(), email.Frecuencia, email.Plantilla, email.Priority, email.Subject, 0, 0);
                RecurringJob.AddOrUpdate(uid, () => BL.PlanesDeAccion.EnvioEmailCustom(IdPlanDeAccion, email.Priority, email.Subject, email.Plantilla), email.Frecuencia, TimeZoneInfo.Local);
            }
            return Json(new JsonResult() { Data = new ML.Result() { Correct = result }, JsonRequestBehavior = JsonRequestBehavior.AllowGet });
        }
        /// <summary>
        /// Obtiene las areas existentes en una bd para crear los planes de accion
        /// </summary>
        /// <param name="IdBaseDeDatos"></param>
        /// <returns></returns>
        public JsonResult GetAreasForPlanAccion(int IdBaseDeDatos)
        {
            bool SA = false;
            int IdCurrentAdmin = Convert.ToInt32(Session["IdAdministradorLogeado"]);
            int IsSA = Convert.ToInt32(Session["SuperAdmin"]);
            if (IsSA == 1)
                SA = true;
            var result = BL.EstructuraAFMReporte.GetEstructuraGAFMForPlanesAccion(IdBaseDeDatos, IdCurrentAdmin, SA);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Retorna la vista de configuracion de permisos a planes de acción
        /// </summary>
        /// <returns></returns>
        public ActionResult ConfigurarPermisos()
        {
            return View();
        }
        /// <summary>
        /// Obtiene el json de estructura organizacional para elegir los permisos
        /// </summary>
        /// <returns></returns>
        public JsonResult ArbolEstructuraModuloPermisosPlanes()
        {
            var result = BL.EstructuraAFMReporte.ArbolEstructuraModuloPermisosPlanes();
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Agrega los permisos a un Area al grupo de administradores seleccionados
        /// </summary>
        /// <param name="Area"></param>
        /// <param name="admins"></param>
        /// <param name="IdBD"></param>
        /// <param name="Direccion"></param>
        /// <param name="Unidad"></param>
        /// <returns></returns>
        public JsonResult AddPermisosPlanes(string Area, int IdBD, List<int> admins, string Direccion, string Unidad)
        {
            string UsuarioActual = Session["AdminLog"] == null ? "Invitado" : Session["AdminLog"].ToString();
            var result = BL.PlanesDeAccion.AddPermisosPlanes(Area, admins, UsuarioActual, IdBD, Direccion, Unidad);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public JsonResult DesactivarPermiso(int IdAdmin, string Area)
        {
            var result = BL.PlanesDeAccion.DesactivarPermiso(IdAdmin, Area);
            return new JsonResult { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Obtiene los admins para el grid de seleccion de asignacion de permisos
        /// </summary>
        /// <param name="Area"></param>
        /// <returns></returns>
        public JsonResult ObtenerAdmins(string Area)
        {
            var result = BL.PlanesDeAccion.ObtenerAdmins(Area);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Obtiene los rangos de promedio establecidos
        /// </summary>
        /// <returns></returns>
        public JsonResult GetRangos()
        {
            var result = BL.PlanesDeAccion.GetRangos();
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Job que genera los promedios generales de cada subcategoria (En desuso porque ya no se invoca manualmente)
        /// </summary>
        /// <param name="promedioSubCategorias"></param>
        /// <returns></returns>
        public JsonResult JobGenerarPromedioSubCategorias(ML.PromedioSubCategorias promedioSubCategorias)
        {
            var result = BL.PlanesDeAccion.JobGenerarPromedioSubCategorias(promedioSubCategorias);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }
        /// <summary>
        /// Consulta los promedios generales de cada subcategoria que generó previamente el job
        /// </summary>
        /// <param name="promedioSubCategorias"></param>
        /// <returns></returns>
        public JsonResult GetSubCategoriasByIdEncuesta(ML.PromedioSubCategorias promedioSubCategorias)
        {
            var result = BL.PlanesDeAccion.GetSubCategoriasByIdEncuesta(promedioSubCategorias);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }
        /// <summary>
        /// Consulta los promedios generales de cada subcategoria de un area especifica
        /// </summary>
        /// <param name="promedioSubCategorias"></param>
        /// <returns></returns>
        public JsonResult GetPromediosSubCategoriasByAreaAgencia(ML.PromedioSubCategorias promedioSubCategorias)
        {
            var result = BL.PlanesDeAccion.GetPromediosSubCategoriasByAreaAgencia(promedioSubCategorias);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }
        /// <summary>
        /// Obtiene las acciones preguardadas
        /// </summary>
        /// <param name="accionDeMejora"></param>
        /// <returns></returns>
        public JsonResult GetAcciones(ML.AccionDeMejora accionDeMejora)
        {
            var result = BL.PlanesDeAccion.GetAcciones(accionDeMejora);
            return new JsonResult() { Data = result, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        /// <summary>
        /// Obtiene las acciones de ayuda
        /// </summary>

PL/Views/PlanesDeAccion/ConfigurarPermisos.cshtml
@model ML.PlanDeAccion
@using Newtonsoft.Json
@{
    ViewBag.Title = "Configurar permisos";
    Layout = "~/Views/Admin/Contenido.cshtml";
}
<script src="~/scripts/ReporteoClima/LinQ.js"></script>
<script src="~/scripts/AngularJS.js"></script>
<script src="~/scripts/swal.min.js"></script>
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.914/styles/kendo.default-main.min.css" />
<script>
    var UserId = @Html.Raw(JsonConvert.SerializeObject(Session["IdAdministradorLogeado"]));
</script>
@section H1{
    <section id="page-title">
        <div class="container-fluid px-lg-5">
            <div class="row">
                <div class="col-6 bottom-align-left center-vertically-xs">
                    <img src="~/img/plan-de-accion-2.png" )" class="img-fluid">
                    <h1 class="title-page-survey">
                        Plan de Acción / <span>Seguimiento</span>
                    </h1>
                </div>
                <div hidden class="col-6 bottom-align-right center-vertically-xs">
                    <a href="#" onclick="GuardarTodo()" class="btn-parallelogram parallelogram">
                        <span class="skew-fix"><i class="fas fa-save"></i> Guardar y cerrar</span>
                    </a>
                </div>
            </div>
        </div><!--.container-fluid-->
    </section>
}
<div hidden class="form-group">
    <input type="file" id="fileChosser2" name="fileChosser2" multiple="multiple" />
    <input type="button" ng-click="vm.AgregarArchivos()" />
</div>
<div id="printDiv" class="content-wrap" ng-app="app" ng-controller="permisosController as vm">
    <div class="container-fluid px-lg-5">
        <div class="row">
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-8">
                        <h3>{{ vm.Modulo }}</h3>
                    </div>
                    <div class="col-4" ng-hide="vm.ListAcciones.length > 0">
                        <input type="button" ng-click="vm.ObtenerAdminElegidos()" class="btn btn-info" value="Agregar permisos" />
                    </div>
                </div>
                <div id="mergePlan" class="row mt-3">
                    <div class="col-1" ng-repeat="item in vm.ListAreas" style="">
                        <input type="button" value="{{ item }}" ng-click="vm.ObtenerAdmins($event)" />
                    </div>  
                </div>
               
                <div class="row">
                    <div class="col-6">
                        <div id="accordion">
                            <div ng-repeat="item in vm.ListPlanesDeAccion track by $index">
                                <div class="card">
                                    <div class="card-header" id="heading{{$index}}">
                                        <h5 class="mb-0">
                                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse{{$index}}" aria-expanded="true" aria-controls="collapse{{$index}}">
                                                {{item.Nombre}}
                                            </button>
                                        </h5>
                                    </div>

                                    <div id="collapse{{$index}}" class="collapse" idBD="{{item.IdBaseDeDatos}}" aria-labelledby="heading{{$index}}" data-parent="#accordion">
                                        <div class="card-body" idbase="{{item.IdBaseDeDatos}}">
                                            <div id="tree-view{{$index}}"></div>
                                            {{vm.consultaAreas(item.Estructura,$index)}}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        @*<div class="divAdmins" style="overflow-y: scroll;max-height: 456px;">
                            <div class="alert alert-info" ng-repeat="item in vm.ListAdmin">
                                {{ item.IdAdministrador }} {{ item.Nombre }} ({{ item.UserName }})
                                <input type="checkbox" id="chkAdmin_{{ item.IdAdministrador }}" value="{{ item.IdAdministrador }}" />
                            </div>
                        </div>*@
                        <div class="row mt-0 mb-0 p-0">
                            <div id="areaSeleccionada" class="col-12 title-header-section title-header-blue mb-0" style="display:none">
                               
                            </div>
                        </div>
                        <div id="gridListAdmin"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/scripts/PlanesDeAccion/AsignarPermisos.js"></script>
<link href="~/scripts/PlanesDeAccion/css/jquery.treeview.css" rel="stylesheet" />
<script src="~/scripts/PlanesDeAccion/js/jquery.treeview.js"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<style>
    .list-acciones span, small{
        display: block;
    }
    .errspan {
        float: right;
        margin-right: 15px;
        margin-top: -25px;
        position: relative;
        z-index: 2;
    }
</style>

PL/Views/PlanesDeAccion/Index.cshtml
@model ML.PlanDeAccion
@using Newtonsoft.Json
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Admin/Contenido.cshtml";
}
<script src="~/scripts/ReporteoClima/LinQ.js"></script>
<script src="~/scripts/AngularJS.js"></script>
<script src="~/scripts/swal.min.js"></script>
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.914/styles/kendo.default-main.min.css" />
<script>
    var IdEncuesta = @Html.Raw(JsonConvert.SerializeObject(Model.IdEncuesta))
    var IdBaseDeDatos = @Html.Raw(JsonConvert.SerializeObject(Model.IdBaseDeDatos))
    var AnioAplicacion = @Html.Raw(JsonConvert.SerializeObject(Model.AnioAplicacion))
</script>

@section H1{
    <section id="page-title">
        <div class="container-fluid px-lg-5">
            <div class="row">
                <div class="col-6 bottom-align-left center-vertically-xs">
                    <img src="../../img/icon-survey.png" )" class="img-fluid">
                    <h1 class="title-page-survey">
                        Plan de Acción / <span>Crear</span>
                    </h1>
                </div>
                <div class="col-6 bottom-align-right center-vertically-xs">
                    <a href="#" onclick="GuardarTodo()" class="btn-parallelogram parallelogram">
                        <span class="skew-fix"><i class="fas fa-save"></i> Guardar y cerrar</span>
                    </a>
                </div>
            </div>
        </div><!--.container-fluid-->
    </section>
}
<div class="content-wrap" ng-app="app" ng-controller="planAccionController as vm">
    @{
        // Acciones para un plan
        if (Model.IdEncuesta == 0)
        {
            <div class="container-fluid px-lg-5">
                <div class="row">
                        <div class="col-lg-10 col-xs-12 col-sm-12">
                            <h2 id="header-modulo" ng-click="vm.ConsultaAccionesGuardadas()">{{ vm.Modulo }}</h2>
                            <div class="form-group">
                                <div class="form-inline">
                                    <div class="col-6">
                                        <h4>Categorias</h4>
                                    </div>
                                    <div class="col-6" style="text-align: end;">
                                        <i class="fa fa-search icon"></i>
                                        <input type="text" style="width: 100%;" class="form-control filter input-field" placeholder="Buscar acciones por palabra clave" />
                                    </div>
                                </div>
                            </div>

                            <!--Despliega las áreas en un arbol de nodos-->
                            <div id="arboles"></div>
                            <div class="col-12 col-sm-12 col-xs-12 col-md-6 col-lg-6 col-xl-6 form-group">
                                <input hidden type="file" accept="" id="postedFile" name="postedFile" class="form-control" />
                                <label id="labelForInputFile" class="mr-3 form-control" for="postedFile">Selecciona un archivo <i class="fas fa-file-excel fa-lg"></i></label>
                                <button class="btn btn-success" onclick="CargaMasiva()">Cargar acciones <i class="fas fa-upload"></i></button>
                                <button class="btn btn-danger" onclick="DownloadLayout()">Descargar layout <i class="fas fa-download"></i></button>
                                <button class="btn btn-info" id="descarga-acciones">Descargar acciones <i class="fas fa-download"></i></button>
                            </div>

                            <div id="accordion">
                                <div id="custom-categoria-{{ item.IdCategoria }}" class="card" style="border-radius: 10px;" ng-repeat="item in vm.Categorias track by $index">
                                    <div class="card-header row col-12" style="left: 15px;" id="headingOne{{ $index }}">
                                        <div class="col-10">
                                            <btn class="btn" data-toggle="collapse" data-target="#collapseOne{{ $index }}" aria-expanded="true" aria-controls="collapseOne{{ $index }}" style="text-align: initial;">
                                                @*({{ item.IdCategoria }})*@ {{ item.Categoria }}
                                            </btn>
                                        </div>
                                        <div class="col-2">
                                            <h5 class="mb-0" style="text-align: end;">
                                                <button title="Agregar nueva acción de mejora" ng-click="vm.AgregarNuevaAccion(item.IdCategoria)" class="btn btn-link" style="border: 1px solid; border-radius: 50%;">
                                                    <i class="fas fa-plus"></i>
                                                </button>
                                            </h5>
                                        </div>
                                    </div>
                                    <div id="collapseOne{{ $index }}" class="collapse" aria-labelledby="headingOne{{ $index }}" data-parent="#accordion">
                                        <div idCategoria="{{ item.IdCategoria }}" id="merge-new-acciones-idcat-{{ item.IdCategoria }}" class="card-body">
                                            <!--Ya no hace la precarga de 4 acciones por default porque carga las acciones preguardadas-->
                                            <!--<div class="form-group" ng-repeat="item in vm.ListRangos track by $index" ng-if="$index < 0">
                                                <div class="form-inline">
                                                    <div class="col-8">
                                                        <input type="text" class="form-control" style="width: 100%;" placeholder="Acción de mejora" />
                                                    </div>
                                                    <div class="col-3">
                                                        <select class="form-control select-rango" style="width: 100%;"></select>
                                                    </div>
                                                    <div class="col-1">
                                                        <button class="btn delete-accion"><i class="fas fa-remove"></i></button>
                                                        <button class="btn save-action" ng-click="vm.GuardarAccion($event)"><i class="fas fa-save"></i></button>
                                                    </div>
                                                </div>
                                            </div>-->
                                        </div>
                                    </div>
                                </div>
                            </div><!--end accordion-->
                        </div>
                    <div class="col-lg-2" id="mergeBusqueda">

                    </div>
                </div>
            </div>
            <div class="modal fade" id="re-asignar-accion">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="alert alert-block">
                                <h4>Reasignar acción</h4>
                            </div>
                            <div class="form-group">
                                <select id="nueva-categoria" class="form-control">
                                    <option value="0">-Selecciona una categoria-</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <select id="nuevo-rango" class="form-control select-rango"></select>
                            </div>
                            <div style="text-align: end;">
                                <button class="btn btn-danger" onclick="LimpiarModal()" style="margin-right: 5px;">Cancelar <i class="fas fa-stop-circle"></i></button>
                                <button class="btn btn-success" ng-click="vm.ReAsignarAccion()">Guardar <i class="fas fa-save"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        // Acciones dadas de alta por Noé
        if (Model.IdEncuesta == -5)
        {
            <div class="container-fluid px-lg-5">
                <div class="row">
                    <div class="col-lg-10">
                        <h2>{{ vm.Modulo }}</h2>
                        <div hidden class="form-group">
                            <button id="nueva-accion" onclick="EditAccionAyuda(this, 'agregar')" class="btn btn-success">Agregar nueva acción <i class="fas fa-plus"></i></button>
                        </div>
                        <div class="form-group">
                            <input type="file" accept="" id="postedFile" name="postedFile" class="form-control" />
                            <input type="button" class="btn btn-info" value="Cargar acciones" onclick="CargaMasiva()" />
                            <br />
                            <input type="button" value="Descargar layout" onclick="Download()" />
                        </div>
                        <div id="grid-Acciones" class="mt-5"></div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="edita-acciones">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">
                            <div class="alert alert-block">
                                <h4 class="header-modal">Editar acción</h4>
                            </div>
                            <div class="form-group">
                                <input type="hidden" class="form-control" />
                            </div>
                            <div class="form-group">
                                <input type="text" placeholder="Descripción de la acción" class="form-control" />
                            </div>
                            <div style="display: none;" class="form-group">
                                <select class="form-control select-rango">
                                </select>
                            </div>
                            <div style="text-align: end;">
                                <button class="btn btn-danger" onclick="LimpiarModal()" style="margin-right: 5px;">Cancelar <i class="fas fa-stop-circle"></i></button>
                                <button class="btn btn-success" ng-click="vm.GuardaAccionAyuda($event)">Guardar <i class="fas fa-save"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>
<div style="display: none;" id="merge-acciones-ayuda">

</div>
<script src="~/scripts/PlanesDeAccion/PlanesDeAccion.js"></script>
<!--Tree view-->
<style>
    .filtera {
        background: url(../../img/ClimaDinamico/icono-buscar.png) no-repeat scroll 7px 7px;
        padding-left: 30px;
    }

    .input-icons i {
        position: absolute;
    }

    .input-icons {
        width: 100%;
        margin-bottom: 10px;
    }

    .icon {
        padding: 10px;
        min-width: 40px;
    }

    .input-field {
        width: 100%;
        padding: 10px;
    }

    .re-asignar-accion {
        cursor: pointer;
    }

    .treeview {
        width: 40%;
    }
    .invalid {
        border-color: #e15858!important;
    }
    .valid {
        border-color: #28a745 !important;
    }
</style>
<link href="~/scripts/PlanesDeAccion/css/jquery.treeview.css" rel="stylesheet" />
<script src="~/scripts/PlanesDeAccion/js/jquery.treeview.js"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<script src="~/scripts/ReporteoClima/html2canvas.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.3/jspdf.min.js"></script>
<script src="~/scripts/ReporteoClima/jspdf.min.js"></script>
<script>
    function DownloadLayout() {
        window.location = "@Url.Action("DescargaL", "PlanesDeAccion")";
    }
</script>